name: Build and Test JavaFX Application

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Specify the operating system for the runner (Ubuntu, Windows, or macOS)
    runs-on: windows-latest  # You can change this to windows-latest or macos-latest if needed

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (You can use other versions if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # You can adjust the version based on your needs
          distribution: 'adoptopenjdk'

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Maven dependencies (skip tests for now)
      - name: Install dependencies
        run: mvn install -DskipTests=true  # Skips tests to speed up dependency installation

      # Step 5: Run the tests (Make sure you have test cases set up)

      # Step 6: Build the project (skip tests here because they are already run)
      - name: Build the project
        run: mvn package -DskipTests=true  # Builds and packages the JavaFX application
