name: Build and Test JavaFX Application manually

on:
  workflow_dispatch:
    inputs:
      LogLevel:
        description: "log level"
        required: true
        default: "warning"
      tags:
        description: "Manual test"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ${{ runner.os == 'Windows' && 'C:/Users/runneradmin/.m2/repository' || '/home/runner/.m2/repository' }}
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests=true

      - name: Run unit tests (JavaFX-safe)
        run: mvn test -Djava.awt.headless=true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Publish test summary
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit

      - name: Build the project
        run: mvn package -DskipTests=true
